apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  # type: ClusterIP change to nodePort for external access
  type: NodePort