apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: ishdocker99/analytics-service:v7
        imagePullPolicy: Always
        env: # <-- Add this section
        - name: CLICKHOUSE_HOST
          value: "10.108.208.118" # <-- Use the CLUSTER-IP you found
        - name: CLICKHOUSE_PASSWORD
          value: "password123"
        ports:
        - containerPort: 5002