apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        env: # <-- Add this section
        - name: CLICKHOUSE_PASSWORD
          value: "password123" # <-- Sets the default user's password to be empty
        ports:
        - name: http
          containerPort: 8123
        - name: client
          containerPort: 9000